// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username           string `json:"username" validate:"required,contains=lpj"`
	Password           string `json:"password" validate:"required"`
	Email              string `json:"email" validate:"email"`
	IsRememberPassword string `json:"is_remember_password" validate:"required,oneof=0 1 2"`
	LtNumber           string `json:"lt_number" validate:"required,lt=3,numeric"`
	GtNumber           int    `json:"gt_number" validate:"required,gt=5"`
	CustomFun          string `json:"customFun" validate:"required,CustomValidateFun"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
